### ISSUE TITLE
Bot / backend

### ISSUE THREAD

**Issue by BlitZz96** [BlitZz96/Twitch-brb#2]
The client is now 90% ready for integration to a bot. ( functionality wise)
The design is still to be made more sexy. However so far, looks pretty damn good. 

How are we gonna go forward with the project and team management? 😊 

Also @Nicholaiii feel free to start fiddling with node/the bot. 
@ngajhede you are more than welcome to change the design etc. 
(if you guys have time and want to that is) :)

**Comment by Nicholaiii** [comment]
I have plenty of time! :) 
I think we can use gitter.im for project/team management? Thought that was pretty relevant since it's pretty common for github projects. I took the liberty of [creating a room right here](https://gitter.im/Twitch-brb/Lobby#) - if you prefer otherwise, I'm pretty much game for anything. Of course TS and/or discord is still an option.

Also maybe Trello, to keep track of whats left to do?

**Comment by ngajhede** [comment]
I created a Trello! What email do you use for Trello?
